### ISSUE TITLE
Random samples become "determined" after adding more workers.

### ISSUE THREAD

**Issue by DongpingQ** [baggepinnen/Hyperopt.jl#38]
Related to #32, I found that using `Random.seed!(0)` does not cause any problem when there is no extra workers. However, when adding more workers, the random samples will become deterministic. See the following simple demonstration:
```
using Distributed
rmprocs(workers()...)

using Hyperopt, Random
function random_samples()
    iters = 10
    Random.seed!(0)
    ho = @phyperopt for i=iters, sampler=CLHSampler(dims=[Categorical(5)]),
                    para = [1,2,3,4,5]
        Random.seed!(0)
        println(para)
    end
end

println("No extra workers: \n")
ho = random_samples()

println("With one worker: \n")
addprocs(1)
@everywhere using Hyperopt, Random
ho = random_samples()
```
You will see that the results from the second `ho` on the added worker becomes identically.

**Comment by pazner** [comment]
I think the issue here is that in `@phyperopt`, in the parallel map, the `ho.history` arrays do not get updated on the main process, and so the samplers are actually reinitializing independently on every worker at every iteration. If the random seed is set every iteration, then the initialization becomes deterministic and you get the same sample every iteration.

It might make sense to manually initialize the sampler before entering the `pmap`, and then pass the iteration state from `Base.iterate(ho::Hyperoptimizer, state)` to the sampler, so that the sampler can use the iteration state as `iter` instead of what is done currently (setting `iter = length(ho.history)+1`) since `ho.history` will always be empty.

If there is interest in this approach, I can submit a PR.

**Comment by baggepinnen** [comment]
Thanks for your bug report and analysis! I'm currently up in the Swedish mountains and can not solve this issue until in a week or so. A PR would be most welcomed, I can easily merge that from here.
