### ISSUE TITLE
Consistency of iteration interface

### ISSUE THREAD

**Issue by mchitre** [baggepinnen/Hyperopt.jl#41]
Given that `Hyperoptimizer` can be used as an iterator, it would be nice for it to be useable in different ways iterators are used. The current behavior works with single-use `for` loops, but does not work well with list comprehensions, with `collect`, `length`, or as part of pipelines.

Examples:
```julia-repl
julia> h = Hyperoptimizer(10, x=randn(100), y=zero(100), z=1:100);

julia> Base.IteratorSize(h)
Base.HasLength()
julia> length(h)       # I would have expected this to be 10
0

julia> collect(h)      # it would be nice to be able to collect the 10 samples
ERROR: ArgumentError: destination has fewer elements than required

julia> length(h)     # the length changed by calling a failed collect
1

julia> [a for a ∈ h]   # I would have expected this to produce 10 samples, since a for loop produces 10 samples
2-element Array{Array{Real,1},1}:
 [1, 1.4863831644285925, 0, 60]
 [2, 2.362371770342243, 0, 68]

julia> [a for a ∈ h]    # calling it again generates 10 samples now, but 2 undef ones!
12-element Array{Array{Real,1},1}:
    [1, -0.2658804004141648, 0, 87]
    [2, 0.010979208480318518, 0, 10]
    [3, 2.038056316399913, 0, 84]
    [4, -1.0823827368014738, 0, 86]
    [5, -0.17462571471167518, 0, 32]
    [6, -1.533831393191818, 0, 26]
    [7, 1.0941017704050044, 0, 21]
    [8, -0.8932412414208927, 0, 53]
    [9, -0.07856351048351846, 0, 52]
    [10, 0.36206459677017444, 0, 18]
 #undef
 #undef
```

Would it make sense to make the `Hyperoptimizer` a fully functional iterator that one could use more flexibly in a machine learning pipeline?

**Comment by baggepinnen** [comment]
I think it would make sense to expose better iterators, and perhaps also make them fundamental to the internals of the package. I recall an old blog post that argues along these lines
http://lostella.github.io/2018/07/25/iterative-methods-done-right.html
but rather than directly working with julias iteration protocol, it would be interesting to make use of something like https://github.com/JuliaFolds/GeneratorsX.jl

This package started out providing only simple "samplers" that were not really optimization algorithms in the traditional sense, they had no feedback from the function being optimized. When I later added the Bayesian algorithm I didn't redesign the internals properly but rather hacked it in. Right now, the optimization loop is constructed in the `@hyperopt` macro. A better approach would be to let the macro simply construct an optimization problem structure that would be sent to a generic `optimize` function that internally dispatches based on the chosen algorithm, similar to how most modern optimization packages in julia are implemented.

**Comment by baggepinnen** [comment]
I believe the code in the OP should be working well now, it was pretty much only `length` that was ill-defined and previously returned the length of the stored results rather than the number of iterations.
