### ISSUE TITLE
`###hyperopt_objective#` not defined On remote worker

### ISSUE THREAD

**Issue by baggepinnen** [baggepinnen/Hyperopt.jl#62]
@ericphanson  wrote
> I can reproduce #58 (comment) in my application on master, and I can use this new RandomSampler on release without issue (just subtyping Sampler from a struct in my application code), so I think it is not an issue introduced by this PR but rather a regression since the v0.4.4 release. I'm having a lot of trouble reproducing it in Hyperopt's tests or a MWE however. One difference is my workers are remote pods in a kubernetes cluster (with K8sClusterManagers). I see a7026b3 touched code that looks relevant, so I wonder if that introduced the issue.

refs https://github.com/baggepinnen/Hyperopt.jl/pull/58#issuecomment-887072000 https://github.com/baggepinnen/Hyperopt.jl/pull/58#issuecomment-887489138

To be investigated further

**Comment by ericphanson** [comment]
in my testing on my internal project, #63 seems to fix this. It's a bit unsatisfying though because we don't have a MWE or test for that issue so can't be sure it will regress. I suspect the difference is between local and remote nodes which have slightly different semantics causing subtle bugs like this.

In my view the long term solution is to make it easy to test Distributed.jl on fake-remote nodes with something like K8sClusterManagers.jl and a wrapper around minikube-- at least, K8sClusterManagers with a real k8s cluster is what I'm using, so that would be a great way to test things for my use-case.
